#
# Copyright (C) 2025 The Android Open Source Project
# Copyright (C) 2025 SebaUbuntu's TWRP device tree generator
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/samsung/m14

# For building with minimal manifest
ALLOW_MISSING_DEPENDENCIES := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := 
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := generic

# Additional
TARGET_USES_UEFI := true
TARGET_IS_64_BIT := true
TARGET_USES_64_BIT_BINDER := true # For android-12.1 and below
TARGET_BOARD_SUFFIX := _64
TARGET_NO_BOOTLOADER := true

# Board
BOARD_USES_QCOM_HARDWARE := true
BOARD_NO_RADIOIMAGE := true
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_SUPPRESS_SECURE_ERASE := true

# Bootloader
BOARD_VENDOR := samsung
TARGET_SOC := bengal
TARGET_BOOTLOADER_BOARD_NAME := $(TARGET_SOC)
TARGET_BOARD_PLATFORM := $(TARGET_SOC)
QCOM_BOARD_PLATFORMS := $(TARGET_SOC)
TARGET_BOARD_PLATFORM_GPU := Adreno-610

# Display (Galaxy M14 4G: 1080x2400)
TW_THEME := portrait_hdpi
TARGET_SCREEN_DENSITY := 403
TARGET_SCREEN_HEIGHT := 2400
TARGET_SCREEN_WIDTH := 1080
TW_BRIGHTNESS_PATH := "/sys/devices/platform/soc/5e00000.qcom,mdss_mdp/backlight/panel0-backlight/brightness"
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 150
TW_FRAMERATE := 90
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888

# Status Bar UI
TW_STATUS_ICONS_ALIGN := center
TW_CUSTOM_CPU_POS := "275"
TW_CUSTOM_CLOCK_POS := "70"
TW_CUSTOM_BATTERY_POS := "790"

# Kernel
BOARD_BOOTIMG_HEADER_VERSION := 4
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_CMDLINE := video=vfb:640x400,bpp=32,memsize=3072000 firmware_class.path=/vendor/firmware,/vendor/firmware_mnt/image,/efs/wifi printk.devkmsg=on bootconfig androidboot.hardware=qcom androidboot.memcg=1 androidboot.usbcontroller=4e00000.dwc3 loop.max_part=7 androidboot.selinux=permissive
BOARD_KERNEL_PAGESIZE := 4096
BOARD_RAMDISK_OFFSET := 0x02000000
BOARD_KERNEL_TAGS_OFFSET := 0x01e00000

# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)

# Kernel Modules
#TW_LOAD_VENDOR_MODULES := true
TW_LOAD_VENDOR_MODULES := $(shell echo \"$(shell ls $(DEVICE_PATH)/recovery/root/lib/modules) $(shell ls $(DEVICE_PATH)/recovery/root/vendor/lib/modules)\")

BOARD_ROOT_EXTRA_FOLDERS := \
    carrier \
    efs \
    omr \
    optics \
    prism \
    spu \
    persist \
    sec_efs \
    firmware \
    metadata \
    keydata \
    keyrefuge

# Copy .idc file 
PRODUCT_COPY_FILES += \
    $(DEVICE_PATH)/recovery/root/system/usr/idc/himax-touchscreen.idc:system/usr/idc/himax-touchscreen.idc \
    $(DEVICE_PATH)/recovery/root/system/usr/idc/himax-touchscreen.idc:$(TARGET_COPY_OUT_VENDOR)/usr/idc/himax-touchscreen.idc

# MKBOOTIMG
BOARD_CUSTOM_BOOTIMG_MK := $(DEVICE_PATH)/mkbootimg.mk

# Partitions
BOARD_FLASH_BLOCK_SIZE := 262144
BOARD_BOOTIMAGE_PARTITION_SIZE := 100663296
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 100663296
BOARD_HAS_LARGE_FILESYSTEM := true

# Filesystem types - MUST match recovery.fstab
BOARD_SYSTEMIMAGE_PARTITION_TYPE := erofs
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_ODMIMAGE_FILE_SYSTEM_TYPE := erofs

# Dynamic partitions
BOARD_SUPER_PARTITION_SIZE := 9126805504
BOARD_SUPER_PARTITION_GROUPS := samsung_dynamic_partitions
BOARD_SAMSUNG_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor system_ext vendor_dlkm product odm
BOARD_SAMSUNG_DYNAMIC_PARTITIONS_SIZE := 9122611200

# Copy out paths
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_PRODUCT := product
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := erofs

# Recovery
RECOVERY_SDCARD_ON_DATA := true
TARGET_RECOVERY_QCOM_RTC_FIX := true
BOARD_INCLUDE_RECOVERY_DTBO := true
BOARD_KERNEL_SEPARATED_DTBO := true

# File System & Storage
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_HAS_LARGE_FILESYSTEM := true
TW_SKIP_ADDITIONAL_FSTAB := true
TW_USE_EXTERNAL_STORAGE := true
TARGET_USES_MKE2FS := true 
TW_INCLUDE_NTFS_3G := true
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery.fstab

# Verified Boot (Simplified to match working TWRP build)
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 0
BOARD_AVB_RECOVERY_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA4096
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := 0
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 0

# Hack: Prevent Anti Rollback
PLATFORM_SECURITY_PATCH := 2099-12-31
VENDOR_SECURITY_PATCH := 2099-12-31
PLATFORM_VERSION := 16.1.0

# Encryption
BOARD_USES_METADATA_PARTITION := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
BOARD_USES_QCOM_FBE_DECRYPTION := true

# USB
TW_USE_NEW_MINADBD := true
TW_EXCLUDE_DEFAULT_USB_INIT := true

# USB OTG Support
TW_EXTERNAL_STORAGE := true

# Misc
TW_INCLUDE_REPACKTOOLS := true
TW_EXTRA_LANGUAGES := true
TW_INCLUDE_LPTOOLS := true
TW_INCLUDE_LPDUMP := true

# TWRP Configuration
TW_SCREEN_BLANK_ON_BOOT := true
TW_INPUT_BLACKLIST := "grip_sensor_wifi","grip_sensor","meta_event","uinput-goodix","fpc_irq@soc:fpc_fp","accelerometer","gyroscope"
TW_USE_TOOLBOX := true
TW_EXCLUDE_APEX := true
TW_NO_BIND_SYSTEM := true
TW_PREPARE_DATA_MEDIA_EARLY := true
TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true
TW_CUSTOM_CPU_TEMP_PATH := "/sys/devices/virtual/thermal/thermal_zone9/temp"
TW_USE_LEGACY_BATTERY_SERVICES := true
TW_NO_HAPTICS := true

# Samsung
TW_NO_REBOOT_BOOTLOADER := true
TW_INCLUDE_FASTBOOTD := true
TW_HAS_DOWNLOAD_MODE := true
TW_USE_SAMSUNG_JDM_HAPTICS := false

# Logging
TARGET_USES_LOGD := true
TWRP_INCLUDE_LOGCAT := true
TWRP_EVENT_LOGGING := true

# Properties
TW_NO_LEGACY_PROPS := true
TW_INCLUDE_LIBRESETPROP := true
TARGET_VENDOR_PROP += $(DEVICE_PATH)/vendor.prop

# Treble
PRODUCT_ENFORCE_VINTF_MANIFEST := true
PRODUCT_FULL_TREBLE := true

# Orangefox
OF_USE_MAGISKBOOT := 1
OF_DISABLE_MIUI_SPECIFIC_FEATURES := "1"
OF_FLASHLIGHT_ENABLE := 0
OF_USE_GREEN_LED := 0
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := 1
OF_DONT_PATCH_ENCRYPTED_DEVICE := 1
OF_DONT_PATCH_ON_FRESH_INSTALLATION := 1
OF_NO_RELOAD_AFTER_DECRYPTION := 1
OF_DEFAULT_KEYMASTER_VERSION := 4.0
OF_SCREEN_H := 2400
OF_STATUS_H := 122
OF_STATUS_INDENT_LEFT := 80
OF_STATUS_INDENT_RIGHT := 80
OF_HIDE_NOTCH := 1
OF_ALLOW_DISABLE_NAVBAR := 0
OF_CHECK_OVERWRITE_ATTEMPTS := 1
OF_FIX_OTA_UPDATE_MANUAL_FLASH_ERROR := 1
OF_DISABLE_MIUI_OTA_BY_DEFAULT := 1
OF_OTA_BACKUP_STOCK_BOOT_IMAGE := 1
OF_RUN_POST_FORMAT_PROCESS := 1
OF_ADVANCED_SECURITY := 1
OF_QUICK_BACKUP_LIST := /boot;/dtbo;
OF_FORCE_PREBUILT_KERNEL := 1
OF_ENABLE_LPTOOLS := 1
OF_SKIP_DECRYPTED_ADOPTED_STORAGE := 1
OF_FIX_DECRYPTION_ON_DATA_MEDIA := 1
OF_UNBIND_SDCARD_F2FS := 1
OF_HAPTICS_ENABLE := 0

# Skyhawk Recovery - ONLY FOR SKYHAWK RECOVERY PROJECT BUILDING
SHRP_DARK := true
SHRP_FLASH_MAX_BRIGHTNESS := 500
SHRP_DEVICE_CODE := m14
SHRP_FLASH := 1

# PBRP- ONLY FOR PITCH BLACK RECOVERY PROJECT BUILDING
PB_TORCH_PATH := "/sys/devices/virtual/camera/flash/rear_flash"
PB_TORCH_MAX_BRIGHTNESS := 1

# Version/Maintainer
TW_DEVICE_VERSION := SavedByLight, Ravindu644, Marine Kitagawa
SHRP_MAINTAINER := SavedByLight, Ravindu644, Marine Kitagawa
OF_MAINTAINER := SavedByLight, Ravindu644, Marine Kitagawa
MAINTAINER := SavedByLight, Ravindu644, Marine Kitagawa

# For testing only
BETA_BUILD := true